modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/azures04/Bawab/issues/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

displayURL="https://github.com/azures04/Bawab/"
logoFile="bawab.png"
credits=""

authors="Azures04"
description='''
Bawab is a mod to prevent /login from microsofts accounts on servers.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"